object Versions {
    const val compose = "1.4.3"
    const val composeMaterial3 = "1.1.1"
    const val composeCompiler = "1.4.6"
    const val hilt = "2.50"
    const val okHttp = "5.0.0-alpha.2"
    const val retrofit = "2.9.0"
    const val gson = "2.8.8"
    const val room = "2.5.0"
    const val hiltnavigation = "1.2.0"
    const val navVersion = "2.8.9"
    const val coilCompose = "2.2.2"
    const val lifecycleViewModelCompose = "2.8.0"
    const val kotlinCoroutinesTest = "1.7.3"
    const val mockitoCore = "5.2.0"
    const val mockitoKotlin = "5.1.0"
    const val archCoreTesting = "2.2.0"
    const val truth = "1.1.3"
}